language: c

install:
  - sudo apt-get update -qq
  - sudo apt-get install --upgrade -y -qq libfftw3-dev cmake

env:
  - CTEST_OUTPUT_ON_FAILURE=1

script:
  - mkdir build && cd build
  - cmake -DUSE_FFTW_FFT=True ../FxDSP && make && ./test/testFxDSP
  - make clean
  - cmake -DUSE_OOURA_FFT=True ../FxDSP && make && ./test/testFxDSP
  

