language: c

install:
  - sudo apt-get update -qq
  - sudo apt-get install --upgrade -y -qq libfftw3-dev cmake

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
  matrix:
    - USE_FFTW_FFT=1
    - USE_OOURA_FFT=1

script:
  - mkdir build && cd build
  - mkdir build && cd build && cmake ../FxDSP && make && ./test/testFxDSP
  

