language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install --upgrade -y -qq libfftw3-dev cmake
script:
  - mkdir build
  - cd build
  - cmake ../FxDSP
  - cmake --build . 
  - env CTEST_OUTPUT_ON_FAILURE=1 make test

