language: c

compiler:
  - clang
  - gcc

install:
  - sudo apt-get update -qq
  - sudo apt-get install --upgrade -y -qq libfftw3-dev cmake

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
  matrix:
    - USE_FFTW_FFT=1
    - USE_OOURA_FFT=1

script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../FxDSP && make && make test-coverage

after_success:
  - cd ..
  - sudo pip install --upgrade pip cpp-coveralls
  - coveralls -r . -e doc -e FxDSP/test -e build/test -e build/CMakeFiles/CompilerId -e build/CMakeFiles/CompilerIdCXX/ --gcov-options '\-lp'


